version: "3.7"

services:
    django_gunicorn:
        volumes:
            - static:/static
            - db:/app/db
            - site_media:/app/site_media
        env_file:
            - .env
        build:
            context: .
        ports:
            - "8080:8080"

    nginx:
        build: ./nginx
        volumes:
            - static:/static
            - site_media:/app/site_media
        ports:
            - "8050:8050"
        depends_on:
            - django_gunicorn

volumes:
    static:
    db:
    site_media:
