# Generated by Django 4.0.1 on 2022-01-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_codesnippet_author_codesnippet_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='title',
            field=models.CharField(default='Code Snippet', max_length=30),
            preserve_default=False,
        ),
    ]
