# Generated by Django 4.0.1 on 2022-01-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_codesnippet_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesnippet',
            name='caption',
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
