# Generated by Django 4.0.1 on 2022-01-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_codesnippet_caption_alter_codesnippet_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
