# Generated by Django 4.0.1 on 2022-01-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_codesnippet_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='language',
            field=models.CharField(default='plaintext', max_length=10),
        ),
    ]
